name: restaurant_app
description: "Simple Design Resto Application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  provider: ^6.1.5+1
  http: ^1.6.0
  sqflite: ^2.4.2
  shared_preferences: ^2.5.4
  flutter_local_notifications: ^20.1.0
  workmanager: ^0.9.0+3
  path: ^1.9.1


dev_dependencies:
  integration_test:
    sdk: flutter

  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  mockito: ^5.6.3
  build_runner: ^2.11.1

flutter:
  uses-material-design: true

  assets:
    - lib/images/